//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TND.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATandC_Cal
    {
        public int No { get; set; }
        public decimal Location_ID { get; set; }
        public int Month { get; set; }
        public int Year { get; set; }
        public int Feeder_Cd { get; set; }
        public string Feeder_Nm { get; set; }
        public Nullable<int> Sent_Out { get; set; }
        public string Payment { get; set; }
        public string Assement { get; set; }
        public string Sold { get; set; }
        public string Collection { get; set; }
        public string UnitRecord { get; set; }
        public Nullable<int> Change_Over { get; set; }
        public string ATandC { get; set; }
    }
}
