//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TND.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Change_Over
    {
        public int No { get; set; }
        public decimal Location_ID { get; set; }
        public int Month { get; set; }
        public int Year { get; set; }
        public int F_Feeder { get; set; }
        public Nullable<int> F_Units { get; set; }
        public Nullable<int> T_Feeder { get; set; }
        public Nullable<int> T_Units { get; set; }
    }
}
