//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TND.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complain
    {
        public decimal Emp_ID { get; set; }
        public string Complain1 { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
