//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TND.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public decimal Emp_ID { get; set; }
        public string Emp_Name { get; set; }
        public int Location { get; set; }
        public string Email_ID { get; set; }
        public Nullable<decimal> Mobile_No { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> Type { get; set; }
        public string Password { get; set; }
        public int Designation { get; set; }
    }
}
