//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TND.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feeder_Master
    {
        public Nullable<decimal> Location_ID { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Sdivn_Cd { get; set; }
        public int Feeder_Code { get; set; }
        public string Feeder_Nm { get; set; }
        public string Feeder_Tp { get; set; }
        public Nullable<int> Capacity { get; set; }
        public string Feeder_Cat { get; set; }
        public Nullable<double> Feeder_Len { get; set; }
        public Nullable<int> Feeder_Ld { get; set; }
        public Nullable<int> Conn_Load { get; set; }
        public Nullable<double> Theo_Loss { get; set; }
        public Nullable<double> Pyear_Loss { get; set; }
        public Nullable<int> Lt_Loc { get; set; }
        public Nullable<int> Lt_Feed { get; set; }
        public int Tr_ss { get; set; }
        public Nullable<int> Tr_Fd { get; set; }
        public Nullable<int> Tr_Sdivn { get; set; }
        public string DFlag { get; set; }
        public Nullable<int> Ysent { get; set; }
        public Nullable<int> Ynagsold { get; set; }
        public Nullable<int> Yhtsold { get; set; }
        public Nullable<int> yagasold { get; set; }
        public Nullable<int> Yagrsold { get; set; }
        public Nullable<double> Yasses { get; set; }
        public Nullable<double> Ycollect { get; set; }
        public Nullable<double> Yarrears { get; set; }
    }
}
