//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TND.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public decimal Location_ID { get; set; }
        public string Location_Name { get; set; }
        public Nullable<decimal> LTLocation_Code { get; set; }
    }
}
