//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TND.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Req_Revert_MonthEnd
    {
        public int Location_ID { get; set; }
        public int Month { get; set; }
        public int Year { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
