//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TND.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ss_Interface
    {
        public int Location_ID { get; set; }
        public int Month { get; set; }
        public int Year { get; set; }
        public decimal Ss_Code { get; set; }
        public int interface_units { get; set; }
        public int No { get; set; }
        public int Feeder_Cd { get; set; }
    }
}
