//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TND.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temp_CPP
    {
        public decimal Location_ID { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Year { get; set; }
        public int S_Div_CD { get; set; }
        public Nullable<int> Feeder_CD { get; set; }
        public Nullable<int> Temp_Units { get; set; }
        public Nullable<double> Temp_Assessment { get; set; }
        public Nullable<double> Temp_Collection { get; set; }
        public Nullable<double> Temp_Arrears { get; set; }
        public Nullable<int> Cpp_Units { get; set; }
        public Nullable<double> Cpp_Assessment { get; set; }
    }
}
