//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TND.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Upload_Data
    {
        public decimal Location_ID { get; set; }
        public string MONTH { get; set; }
        public string YEAR { get; set; }
        public string CIRCLE_CODE { get; set; }
        public string CIRCLE_NAME { get; set; }
        public string DIVISION_CODE { get; set; }
        public string DIVISION_NAME { get; set; }
        public string SUBDIV_CODE { get; set; }
        public string SUBDIV_NAME { get; set; }
        public string LOCATION_CODE { get; set; }
        public string CONSUMER_NO { get; set; }
        public string CONSUMER_NAME { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string CENCUS_CODE { get; set; }
        public string TRANS_LOCATION { get; set; }
        public string SD_AMOUNT { get; set; }
        public string CONNECTION_DATE { get; set; }
        public string POLE_CODE { get; set; }
        public string PDC_DATE { get; set; }
        public string IND_TYPE { get; set; }
        public string SEASONAL_IND { get; set; }
        public string SD_AMOUNT_RECEIPT_DATE { get; set; }
        public string SD_AMOUNT_RECEIPT_NO { get; set; }
        public string CONTRACT_LOAD { get; set; }
        public string TARRIF { get; set; }
        public string CYCLE_NO { get; set; }
        public string METER_READER_NO { get; set; }
        public string BOOK_NO { get; set; }
        public string ROUTE_CODE { get; set; }
        public string METER_NO { get; set; }
        public string METER_STATUS { get; set; }
        public string EDUTY_CODE { get; set; }
        public string EDUTY_AMOUNT { get; set; }
        public string CONTRACT_DEMAND { get; set; }
        public string FEEDER_NO { get; set; }
        public string PHASE { get; set; }
        public string METER_RENT_TYPE { get; set; }
        public string THEFT_ARREARS { get; set; }
        public string LITIGATION_ARREARS { get; set; }
        public string FIXED_CHG { get; set; }
        public string FUEL_CHG { get; set; }
        public string FUSE_CHG { get; set; }
        public string CREDIT_ADJUSTMENT { get; set; }
        public string DEBIT_ADJUSTMENT { get; set; }
        public string CLOSING_ARREARS { get; set; }
        public string CONSUMPTION_UNIT { get; set; }
        public string ASSESSMENT_UNIT { get; set; }
        public string DPC_AMOUNT { get; set; }
        public string RELIEF_AMOUNT { get; set; }
        public string ENERGY_CHARGE { get; set; }
        public string BOARD_CHARGE { get; set; }
        public string PROV_BILL_AMOUNT { get; set; }
        public string PAYMENT_AMOUNT { get; set; }
        public string BILL_AMOUNT { get; set; }
        public string START_METER { get; set; }
        public string END_METER { get; set; }
        public string AVG_UNIT { get; set; }
        public string RE_START_READING { get; set; }
        public string RE_END_READING { get; set; }
        public string RE_CONSUMPTION { get; set; }
        public string BILL_DATE { get; set; }
        public string DUE_DATE { get; set; }
        public string PAYMENT_DATE { get; set; }
        public string FEEDER_CODE { get; set; }
        public string FEEDER_NAME { get; set; }
        public string VILLAGE_NAME { get; set; }
        public string TARRIF_SHORT { get; set; }
        public string METER_CHANGE_DATE { get; set; }
        public string ADJUSTMENT_UNIT { get; set; }
        public string OLD_TARIFF_IND { get; set; }
        public string BILL_DEMAND { get; set; }
        public string BILL_TYPE { get; set; }
        public string STATUS { get; set; }
        public string LAST_PAYDATE { get; set; }
    }
}
